### ISSUE TITLE
Add "RADAR-base Data Uploader" to RADAR base platform

### ISSUE THREAD

**Issue by ajitesh18** [RADAR-base/radar-upload-source-connector#116]
Since we have other connectors available in the RADAR base platform package, it would be helpful if we can include Data upload connector as well to avoid multiple docker-compose files (dependencies are somewhat similar). Please let me know if it is possible. Thank you.

**Comment by nivemaham** [comment]
We are moving towards Kubernetes based deployment. Latest components have been added to RADAR-Kubernetes.
Please follow https://github.com/RADAR-base/RADAR-Kubernetes for more details.
