### ISSUE TITLE
Record status is SUCCEEDED even when one of the files failed to process

### ISSUE THREAD

**Issue by mpgxvii** [RADAR-base/radar-upload-source-connector#176]
- When a record has multiple files and one of the files fails to be processed/converted, but the rest of the files are successfully processed, the record status is still `SUCCEEDED`.

**Comment by blootsvoets** [comment]
Should be fixed by #177. Indeed there was a bug that each file in a record that was successfully processed would cause the entire record to be marked as successful. This should now be resolved.

**Comment by mpgxvii** [comment]
Okay great thanks.
