### ISSUE TITLE
Zip files fail to process when there are extra files

### ISSUE THREAD

**Issue by mpgxvii** [RADAR-base/radar-upload-source-connector#179]
- Zip files fail to process when there are extra unexpected files inside
- For example, here, an extra `MOTOR_BUBBLE.csv` file is included when only 13 csvLineProcessors are available for the zip file:
`Cannot find data processor for record 1490 with file 2021[...]_research_participant_MOTOR_BUBBLE.csvorg.radarbase.connect.upload.exception.DataProcessorNotFoundException: Cannot find data processor for record 1490 with file 20210331091214_xxx_research-participant_MOTOR_BUBBLE.csv`

Edit: removed email address from issue.

**Comment by mpgxvii** [comment]
@blootsvoets Can we just ignore the extra file and proceed?

**Comment by blootsvoets** [comment]
Sounds OK, on a per-source-type basis. Could you implement this change? A constructor property in ZipFileProceccorFactory like `allowUnmappedFiles: Boolean`?

**Comment by mpgxvii** [comment]
> Sounds OK, on a per-source-type basis. Could you implement this change? A constructor property in `ZipFileProcessorFactory` like `allowUnmappedFiles: Boolean`?

Sure I can make the changes.

**Comment by mpgxvii** [comment]
Solved in #180
