### ISSUE TITLE
Allow deleting records that are INCOMPLETE from UI

### ISSUE THREAD

**Issue by nivemaham** [RADAR-base/radar-upload-source-connector#50]
I think we should be able to delete records that are FAILED and INCOMPLETE. Maybe even READY. But not the rest.
@blootsvoets What do you think?

**Comment by khoathanglong** [comment]
Could you guys spend time making API for this first?

**Comment by blootsvoets** [comment]
There is an API call `DELETE /records/{recordId}` for deleting a record and `DELETE /records/{recordId}/contents/{fileName}` for deleting a single file. You can delete file contents only if the record is `INCOMPLETE`. You can delete a record if it is not in state `PROCESSING`.

**Comment by khoathanglong** [comment]
Deleting record error: `[409] incompatible_revision: Revision in metadata 1 does not match provided revision 0`

**Comment by nivemaham** [comment]
Fixed by #96
