### ISSUE TITLE
Better rendering of logs

### ISSUE THREAD

**Issue by nivemaham** [RADAR-base/radar-upload-source-connector#53]
Currently the  upload back-end stores logs as a CLOB that has a JSON string of logs. The upload front-end renders the escaped JSON string as it is. This can be improved to a better format.  
![image](https://user-images.githubusercontent.com/1315378/64627173-724ffd00-d3ef-11e9-8a46-84caabafa442.png)

**Comment by blootsvoets** [comment]
Perhaps on the backend, use a (possibly configurable) logging notation? e.g. 
```
{dateTime} [{logLevel}] {message}
```
Alternatively, we could add JSON semantics to the log storage... In any case, the window should just contain the text in the `contents` field, not all the text around it. The converter should only PUT the contents of the file, not the RecordContents JSON object.
