### ISSUE TITLE
use of serviceWorker.js on the frontend app

### ISSUE THREAD

**Issue by nivemaham** [RADAR-base/radar-upload-source-connector#59]
What is the actual reason and use of having to register the `serviceWorker.js` on this app? 
Does it do anything apart from caching? if so what exactly? 
From what I understand it allows some offline communication, which I am not sure if we need it for our use-case. Further, it is confusing when the app can still be used by the browser, when the app has been stopped on the server. 
If we want to reload changes on the browser, I have to go on incognito tab or close the tab and reopen a new tab (even this sometimes doesn't work). This cannot be expected from end-user. I do not want to have a situation where the actual deployment of the app is not 100% sycn with the deployed version. 
I would like to understand the actual purpose behind it and reevaluate if we actually need it?

@blootsvoets @khoathanglong

**Comment by khoathanglong** [comment]
It's just the initial setup in case we need it. For now you can press Ctrl+F5 to load the updated code.
