### ISSUE TITLE
API to get list of status

### ISSUE THREAD

**Issue by khoathanglong** [RADAR-base/radar-upload-source-connector#84]
For user to select a status to filter the records, I think we should have an API to get the status list

**Comment by blootsvoets** [comment]
You mean the statuses that are currently active?

**Comment by khoathanglong** [comment]
All the statuses that Get /records support

**Comment by blootsvoets** [comment]
All the supported statuses can be hardcoded in the frontend. These projects are supported in the same repository anyway.

**Comment by khoathanglong** [comment]
Yes for now I can hardcode the statuses in the frontend but I dont think it's a good idea. In case statuses change or more status added require to update the UI accordingly. User possibly requires the feature to change the status name themselves.

**Comment by blootsvoets** [comment]
OK I think this will not be implemented in the near future.
